module.exports = {
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  transform: {
    "^.+\\.[jt]sx?$": "babel-jest",
  },
  moduleNameMapper: {
    "^react$": "<rootDir>/node_modules/react",
    "^react/(.*)$": "<rootDir>/node_modules/react/$1",
    "^react-dom$": "<rootDir>/node_modules/react-dom",
    "^react-dom/(.*)$": "<rootDir>/node_modules/react-dom/$1",
    "\\.(css|less|scss|sass)$": "<rootDir>/test/styleMock.js",
    "\\.(gif|ttf|eot|svg|png|jpg|jpeg|webp)$": "<rootDir>/test/fileMock.js",
  },
  collectCoverageFrom: [
    "src/assets/components/**/*.{js,jsx}",
    "src/assets/layout/**/*.{js,jsx}",
    "src/assets/pages/about/**/*.{js,jsx}",
    "src/assets/pages/contact/**/*.{js,jsx}",
    "src/assets/pages/create-list/**/*.{js,jsx}",
    "src/assets/pages/create-task/**/*.{js,jsx}",
    "src/assets/pages/dashboard/**/*.{js,jsx}",
    "src/assets/pages/edit-profile/**/*.{js,jsx}",
    "src/assets/pages/landing/**/*.{js,jsx}",
    "src/assets/pages/login/**/*.{js,jsx}",
    "src/assets/pages/recover-password/**/*.{js,jsx}",
    "src/assets/pages/reset-password/**/*.{js,jsx}",
    "src/assets/pages/tasks/**/*.{js,jsx}",
    "!src/assets/pages/services/**",
    "!src/assets/pages/api/**",
    "!src/**/*.css",
    "!src/main.jsx",
    "!src/App.jsx",
  ],
  testMatch: ["<rootDir>/src/**/*.test.{js,jsx}", "<rootDir>/src/**/*.spec.{js,jsx}"],
};